# Welcome to Serverless!

service: i2btanode-template

provider:
  name: aws
  runtime: nodejs12.x

functions:  
login:
  handler: src/api-client/rest/app.authentication
  events:      
    - http:
        path: authentication                         
        method: POST  
plugins:
- serverless-offline